/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
	_type: "sanity.imagePaletteSwatch";
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: "sanity.imagePalette";
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: "sanity.imageDimensions";
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type BehindTheScenesBlock = {
	_type: "behindTheScenesBlock";
	title?: string;
	description?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: "span";
			_key: string;
		}>;
		style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
		listItem?: "bullet" | "number";
		markDefs?: Array<{
			href?: string;
			_type: "link";
			_key: string;
		}>;
		level?: number;
		_type: "block";
		_key: string;
	}>;
	images?: Array<{
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
		_key: string;
	}>;
};

export type TechSpecsBlock = {
	_type: "techSpecsBlock";
	title?: string;
	specs?: Array<{
		label?: string;
		value?: string;
		_type: "spec";
		_key: string;
	}>;
	layout?: "table" | "list";
};

export type FeaturedImageBlock = {
	_type: "featuredImageBlock";
	image?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
	};
	size?: "standard" | "large" | "fullWidth";
	imageMetadata?: {
		camera?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "camera";
		};
		lens?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "lens";
		};
		aperture?: string;
		shutterSpeed?: string;
		iso?: number;
	};
	showMetadata?: boolean;
};

export type QuoteBlock = {
	_type: "quoteBlock";
	quote?: string;
	attribution?: string;
	style?: "simple" | "pullQuote" | "blockquote";
};

export type DividerBlock = {
	_type: "dividerBlock";
	style?: "line" | "dots" | "stars" | "space";
};

export type DemoBlock = {
	_type: "demoBlock";
	type?: string;
	heading?: string;
	demoType?: "Video" | "Interactive" | "Screenshot Tour";
	demoContent?: Array<
		| {
				asset?: {
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
				};
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: "image";
				_key: string;
		  }
		| {
				asset?: {
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: "sanity.fileAsset";
				};
				_type: "file";
				_key: string;
		  }
		| {
				url?: string;
				_type: "embeddedVideo";
				_key: string;
		  }
	>;
};

export type RepoLinkBlock = {
	_type: "repoLinkBlock";
	type?: string;
	heading?: string;
	repository?: string;
	liveUrl?: string;
};

export type ChallengeBlock = {
	_type: "challengeBlock";
	type?: string;
	heading?: string;
	challenges?: Array<{
		problem?: string;
		solution?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
		_key: string;
	}>;
};

export type ProcessBlock = {
	_type: "processBlock";
	type?: string;
	heading?: string;
	phases?: Array<{
		phase?: string;
		description?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
		_key: string;
	}>;
};

export type StackBlock = {
	_type: "stackBlock";
	type?: string;
	heading?: string;
	technologies?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "softwareType";
	}>;
};

export type CodeBlock = {
	_type: "codeBlock";
	code?: string;
	language?: "javascript" | "typescript" | "html" | "css" | "python";
};

export type GalleryBlock = {
	_type: "galleryBlock";
	images?: Array<{
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
		_key: string;
	}>;
	layout?: "grid" | "masonry" | "slider";
};

export type ImageBlock = {
	_type: "imageBlock";
	image?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
	caption?: string;
	alt?: string;
	width?: "normal" | "wide" | "full";
};

export type TextBlock = {
	_type: "textBlock";
	content?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: "span";
			_key: string;
		}>;
		style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
		listItem?: "bullet" | "number";
		markDefs?: Array<{
			href?: string;
			_type: "link";
			_key: string;
		}>;
		level?: number;
		_type: "block";
		_key: string;
	}>;
	width?: "normal" | "wide" | "full";
};

export type HeadlineBlock = {
	_type: "headlineBlock";
	headline?: string;
	size?:
		| "text-lg font-semibold"
		| "text-xl font-semibold"
		| "text-2xl font-bold"
		| "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight";
	alignment?: "text-left" | "text-center" | "text-right";
	width?: "normal" | "wide" | "full";
};

export type Handcrafted = {
	_id: string;
	_type: "handcrafted";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	publishedAt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
	};
	author?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	};
	excerpt?: string;
	content?: Array<
		| {
				headline?: string;
				size?:
					| "text-lg font-semibold"
					| "text-xl font-semibold"
					| "text-2xl font-bold"
					| "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight";
				alignment?: "text-left" | "text-center" | "text-right";
				width?: "normal" | "wide" | "full";
				_type: "headlineBlock";
				_key: string;
		  }
		| {
				content?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				width?: "normal" | "wide" | "full";
				_type: "textBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
				};
				size?: "standard" | "large" | "fullWidth";
				imageMetadata?: {
					camera?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "camera";
					};
					lens?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "lens";
					};
					aperture?: string;
					shutterSpeed?: string;
					iso?: number;
				};
				showMetadata?: boolean;
				_type: "featuredImageBlock";
				_key: string;
		  }
		| {
				style?: "line" | "dots" | "stars" | "space";
				_type: "dividerBlock";
				_key: string;
		  }
		| {
				quote?: string;
				attribution?: string;
				style?: "simple" | "pullQuote" | "blockquote";
				_type: "quoteBlock";
				_key: string;
		  }
		| {
				title?: string;
				description?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				images?: Array<{
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
					_key: string;
				}>;
				_type: "behindTheScenesBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				challenges?: Array<{
					problem?: string;
					solution?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "challengeBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				demoType?: "Video" | "Interactive" | "Screenshot Tour";
				demoContent?: Array<
					| {
							asset?: {
								_ref: string;
								_type: "reference";
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
							};
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: "image";
							_key: string;
					  }
					| {
							asset?: {
								_ref: string;
								_type: "reference";
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: "sanity.fileAsset";
							};
							_type: "file";
							_key: string;
					  }
					| {
							url?: string;
							_type: "embeddedVideo";
							_key: string;
					  }
				>;
				_type: "demoBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				phases?: Array<{
					phase?: string;
					description?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "processBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				repository?: string;
				liveUrl?: string;
				_type: "repoLinkBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				technologies?: Array<{
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					_key: string;
					[internalGroqTypeReferenceTo]?: "softwareType";
				}>;
				_type: "stackBlock";
				_key: string;
		  }
		| {
				title?: string;
				specs?: Array<{
					label?: string;
					value?: string;
					_type: "spec";
					_key: string;
				}>;
				layout?: "table" | "list";
				_type: "techSpecsBlock";
				_key: string;
		  }
	>;
	tags?: Array<string>;
};

export type Development = {
	_id: string;
	_type: "development";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	publishedAt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
	};
	author?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	};
	excerpt?: string;
	projectStatus?: "inProgress" | "completed" | "maintenance" | "archived";
	projectDuration?: {
		startDate?: string;
		endDate?: string;
		timeSpent?: string;
	};
	clientName?: string;
	projectLink?: string;
	projectType?:
		| "webApp"
		| "website"
		| "mobileApp"
		| "desktopApp"
		| "apiBackend"
		| "browserExtension"
		| "library"
		| "game"
		| "other";
	content?: Array<
		| {
				headline?: string;
				size?:
					| "text-lg font-semibold"
					| "text-xl font-semibold"
					| "text-2xl font-bold"
					| "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight";
				alignment?: "text-left" | "text-center" | "text-right";
				width?: "normal" | "wide" | "full";
				_type: "headlineBlock";
				_key: string;
		  }
		| {
				content?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				width?: "normal" | "wide" | "full";
				_type: "textBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
				};
				caption?: string;
				alt?: string;
				width?: "normal" | "wide" | "full";
				_type: "imageBlock";
				_key: string;
		  }
		| {
				images?: Array<{
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
					_key: string;
				}>;
				layout?: "grid" | "masonry" | "slider";
				_type: "galleryBlock";
				_key: string;
		  }
		| {
				code?: string;
				language?: "javascript" | "typescript" | "html" | "css" | "python";
				_type: "codeBlock";
				_key: string;
		  }
		| {
				style?: "line" | "dots" | "stars" | "space";
				_type: "dividerBlock";
				_key: string;
		  }
		| {
				quote?: string;
				attribution?: string;
				style?: "simple" | "pullQuote" | "blockquote";
				_type: "quoteBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
				};
				size?: "standard" | "large" | "fullWidth";
				imageMetadata?: {
					camera?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "camera";
					};
					lens?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "lens";
					};
					aperture?: string;
					shutterSpeed?: string;
					iso?: number;
				};
				showMetadata?: boolean;
				_type: "featuredImageBlock";
				_key: string;
		  }
		| {
				title?: string;
				specs?: Array<{
					label?: string;
					value?: string;
					_type: "spec";
					_key: string;
				}>;
				layout?: "table" | "list";
				_type: "techSpecsBlock";
				_key: string;
		  }
		| {
				title?: string;
				description?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				images?: Array<{
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
					_key: string;
				}>;
				_type: "behindTheScenesBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				challenges?: Array<{
					problem?: string;
					solution?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "challengeBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				demoType?: "Video" | "Interactive" | "Screenshot Tour";
				demoContent?: Array<
					| {
							asset?: {
								_ref: string;
								_type: "reference";
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
							};
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: "image";
							_key: string;
					  }
					| {
							asset?: {
								_ref: string;
								_type: "reference";
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: "sanity.fileAsset";
							};
							_type: "file";
							_key: string;
					  }
					| {
							url?: string;
							_type: "embeddedVideo";
							_key: string;
					  }
				>;
				_type: "demoBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				phases?: Array<{
					phase?: string;
					description?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "processBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				repository?: string;
				liveUrl?: string;
				_type: "repoLinkBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				technologies?: Array<{
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					_key: string;
					[internalGroqTypeReferenceTo]?: "softwareType";
				}>;
				_type: "stackBlock";
				_key: string;
		  }
	>;
	techStack?: {
		frontend?: Array<{
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			_key: string;
			[internalGroqTypeReferenceTo]?: "softwareType";
		}>;
		backend?: Array<{
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			_key: string;
			[internalGroqTypeReferenceTo]?: "softwareType";
		}>;
		database?: Array<{
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			_key: string;
			[internalGroqTypeReferenceTo]?: "softwareType";
		}>;
		devOps?: Array<{
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			_key: string;
			[internalGroqTypeReferenceTo]?: "softwareType";
		}>;
	};
	frameworks?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "softwareType";
	}>;
	libraries?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "softwareType";
	}>;
	hostingPlatform?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "softwareType";
	};
	tags?: Array<string>;
};

export type SoftwareType = {
	_id: string;
	_type: "softwareType";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	description?: string;
	icon?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
	};
};

export type Design = {
	_id: string;
	_type: "design";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	publishedAt?: string;
	author?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	};
	designTeam?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "author";
	}>;
	excerpt?: string;
	projectStatus?: "inProgress" | "completed" | "maintenance" | "archived";
	projectDuration?: {
		startDate?: string;
		endDate?: string;
		timeSpent?: string;
	};
	client?: {
		name?: string;
		industry?: string;
		website?: string;
	};
	category?:
		| "Brand Identity"
		| "Web Design"
		| "UI/UX Design"
		| "Print Design"
		| "Marketing Design"
		| "Packaging Design"
		| "Environmental Design"
		| "Motion Design";
	tags?: Array<string>;
	tools?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "softwareType";
	}>;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
	};
	content?: Array<
		| {
				headline?: string;
				size?:
					| "text-lg font-semibold"
					| "text-xl font-semibold"
					| "text-2xl font-bold"
					| "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight";
				alignment?: "text-left" | "text-center" | "text-right";
				width?: "normal" | "wide" | "full";
				_type: "headlineBlock";
				_key: string;
		  }
		| {
				content?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				width?: "normal" | "wide" | "full";
				_type: "textBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
				};
				caption?: string;
				alt?: string;
				width?: "normal" | "wide" | "full";
				_type: "imageBlock";
				_key: string;
		  }
		| {
				images?: Array<{
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
					_key: string;
				}>;
				layout?: "grid" | "masonry" | "slider";
				_type: "galleryBlock";
				_key: string;
		  }
		| {
				style?: "line" | "dots" | "stars" | "space";
				_type: "dividerBlock";
				_key: string;
		  }
		| {
				quote?: string;
				attribution?: string;
				style?: "simple" | "pullQuote" | "blockquote";
				_type: "quoteBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
				};
				size?: "standard" | "large" | "fullWidth";
				imageMetadata?: {
					camera?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "camera";
					};
					lens?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "lens";
					};
					aperture?: string;
					shutterSpeed?: string;
					iso?: number;
				};
				showMetadata?: boolean;
				_type: "featuredImageBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				phases?: Array<{
					phase?: string;
					description?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "processBlock";
				_key: string;
		  }
		| {
				title?: string;
				description?: string;
				beforeImage?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
				};
				afterImage?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
				};
				_type: "beforeAfterBlock";
				_key: string;
		  }
		| {
				quote?: string;
				author?: string;
				role?: string;
				company?: string;
				avatar?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
				};
				_type: "testimonialBlock";
				_key: string;
		  }
		| {
				title?: string;
				description?: string;
				devices?: Array<{
					deviceType?:
						| "Desktop"
						| "Tablet"
						| "Mobile"
						| "Watch"
						| "TV"
						| "Other";
					image?: {
						asset?: {
							_ref: string;
							_type: "reference";
							_weak?: boolean;
							[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
						};
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						alt?: string;
						_type: "image";
					};
					notes?: string;
					_key: string;
				}>;
				_type: "responsiveDesignBlock";
				_key: string;
		  }
		| {
				title?: string;
				description?: string;
				iterations?: Array<{
					version?: string;
					date?: string;
					image?: {
						asset?: {
							_ref: string;
							_type: "reference";
							_weak?: boolean;
							[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
						};
						hotspot?: SanityImageHotspot;
						crop?: SanityImageCrop;
						_type: "image";
					};
					changes?: string;
					feedback?: string;
					_key: string;
				}>;
				_type: "iterationBlock";
				_key: string;
		  }
	>;
	caseStudy?: {
		problem?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
		approach?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
		solution?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
		results?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
	};
	gallery?: Array<{
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		span?: "" | "col-span-2";
		_type: "image";
		_key: string;
	}>;
	process?: Array<{
		phase?: string;
		description?: Array<{
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<{
				href?: string;
				_type: "link";
				_key: string;
			}>;
			level?: number;
			_type: "block";
			_key: string;
		}>;
		artifacts?: Array<{
			media?: {
				asset?: {
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
				};
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: "image";
			};
			_key: string;
		}>;
		_key: string;
	}>;
	designSystem?: {
		colors?: Array<{
			name?: string;
			hex?: string;
			description?: string;
			_key: string;
		}>;
		typography?: {
			primaryFont?: {
				name?: string;
				description?: string;
				weights?: Array<number>;
				sizes?: Array<{
					name?:
						| "Display"
						| "H1"
						| "H2"
						| "H3"
						| "H4"
						| "H5"
						| "H6"
						| "Body"
						| "Small"
						| "Caption";
					size?: number;
					lineHeight?: number;
					_key: string;
				}>;
			};
			secondaryFont?: {
				name?: string;
				description?: string;
				weights?: Array<number>;
				sizes?: Array<{
					name?:
						| "Display"
						| "H1"
						| "H2"
						| "H3"
						| "H4"
						| "H5"
						| "H6"
						| "Body"
						| "Small"
						| "Caption";
					size?: number;
					lineHeight?: number;
					_key: string;
				}>;
			};
		};
		logos?: Array<{
			name?: string;
			image?: {
				asset?: {
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
				};
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: "image";
			};
			usage?: string;
			_key: string;
		}>;
	};
};

export type Photography = {
	_id: string;
	_type: "photography";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	publishedAt?: string;
	mainImage?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: "image";
	};
	author?: {
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: "author";
	};
	excerpt?: string;
	content?: Array<
		| {
				headline?: string;
				size?:
					| "text-lg font-semibold"
					| "text-xl font-semibold"
					| "text-2xl font-bold"
					| "text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight";
				alignment?: "text-left" | "text-center" | "text-right";
				width?: "normal" | "wide" | "full";
				_type: "headlineBlock";
				_key: string;
		  }
		| {
				content?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				width?: "normal" | "wide" | "full";
				_type: "textBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
				};
				caption?: string;
				alt?: string;
				width?: "normal" | "wide" | "full";
				_type: "imageBlock";
				_key: string;
		  }
		| {
				images?: Array<{
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
					_key: string;
				}>;
				layout?: "grid" | "masonry" | "slider";
				_type: "galleryBlock";
				_key: string;
		  }
		| {
				code?: string;
				language?: "javascript" | "typescript" | "html" | "css" | "python";
				_type: "codeBlock";
				_key: string;
		  }
		| {
				style?: "line" | "dots" | "stars" | "space";
				_type: "dividerBlock";
				_key: string;
		  }
		| {
				quote?: string;
				attribution?: string;
				style?: "simple" | "pullQuote" | "blockquote";
				_type: "quoteBlock";
				_key: string;
		  }
		| {
				image?: {
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
				};
				size?: "standard" | "large" | "fullWidth";
				imageMetadata?: {
					camera?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "camera";
					};
					lens?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "lens";
					};
					aperture?: string;
					shutterSpeed?: string;
					iso?: number;
				};
				showMetadata?: boolean;
				_type: "featuredImageBlock";
				_key: string;
		  }
		| {
				title?: string;
				specs?: Array<{
					label?: string;
					value?: string;
					_type: "spec";
					_key: string;
				}>;
				layout?: "table" | "list";
				_type: "techSpecsBlock";
				_key: string;
		  }
		| {
				title?: string;
				description?: Array<{
					children?: Array<{
						marks?: Array<string>;
						text?: string;
						_type: "span";
						_key: string;
					}>;
					style?:
						| "normal"
						| "h1"
						| "h2"
						| "h3"
						| "h4"
						| "h5"
						| "h6"
						| "blockquote";
					listItem?: "bullet" | "number";
					markDefs?: Array<{
						href?: string;
						_type: "link";
						_key: string;
					}>;
					level?: number;
					_type: "block";
					_key: string;
				}>;
				images?: Array<{
					asset?: {
						_ref: string;
						_type: "reference";
						_weak?: boolean;
						[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
					};
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					alt?: string;
					caption?: string;
					_type: "image";
					_key: string;
				}>;
				_type: "behindTheScenesBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				challenges?: Array<{
					problem?: string;
					solution?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "challengeBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				demoType?: "Video" | "Interactive" | "Screenshot Tour";
				demoContent?: Array<
					| {
							asset?: {
								_ref: string;
								_type: "reference";
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
							};
							hotspot?: SanityImageHotspot;
							crop?: SanityImageCrop;
							_type: "image";
							_key: string;
					  }
					| {
							asset?: {
								_ref: string;
								_type: "reference";
								_weak?: boolean;
								[internalGroqTypeReferenceTo]?: "sanity.fileAsset";
							};
							_type: "file";
							_key: string;
					  }
					| {
							url?: string;
							_type: "embeddedVideo";
							_key: string;
					  }
				>;
				_type: "demoBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				phases?: Array<{
					phase?: string;
					description?: Array<{
						children?: Array<{
							marks?: Array<string>;
							text?: string;
							_type: "span";
							_key: string;
						}>;
						style?:
							| "normal"
							| "h1"
							| "h2"
							| "h3"
							| "h4"
							| "h5"
							| "h6"
							| "blockquote";
						listItem?: "bullet" | "number";
						markDefs?: Array<{
							href?: string;
							_type: "link";
							_key: string;
						}>;
						level?: number;
						_type: "block";
						_key: string;
					}>;
					_key: string;
				}>;
				_type: "processBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				repository?: string;
				liveUrl?: string;
				_type: "repoLinkBlock";
				_key: string;
		  }
		| {
				type?: string;
				heading?: string;
				technologies?: Array<{
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					_key: string;
					[internalGroqTypeReferenceTo]?: "softwareType";
				}>;
				_type: "stackBlock";
				_key: string;
		  }
	>;
	location?: {
		name?: string;
		city?: string;
		country?: string;
		coordinates?: Geopoint;
	};
	tags?: Array<string>;
	shootMetadata?: {
		theme?:
			| "Landscape"
			| "Portrait"
			| "Street"
			| "Architecture"
			| "Nature"
			| "Wildlife"
			| "Travel"
			| "Event"
			| "Abstract"
			| "Documentary"
			| "Other";
		equipment?: {
			cameras?: Array<{
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: "camera";
			}>;
			lenses?: Array<{
				_ref: string;
				_type: "reference";
				_weak?: boolean;
				_key: string;
				[internalGroqTypeReferenceTo]?: "lens";
			}>;
		};
		technicalNotes?: string;
	};
};

export type Geopoint = {
	_type: "geopoint";
	lat?: number;
	lng?: number;
	alt?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: "sanity.fileAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type Lens = {
	_id: string;
	_type: "lens";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	brand?: string;
	focalLength?: {
		min?: string;
		max?: string;
	};
	maxAperture?: string;
};

export type Camera = {
	_id: string;
	_type: "camera";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	brand?: string;
	modelNumber?: string;
	type?: "DSLR" | "Mirrorless" | "Film" | "Medium Format" | "Other";
};

export type Author = {
	_id: string;
	_type: "author";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name?: string;
	image?: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: "image";
	};
};

export type SanityImageCrop = {
	_type: "sanity.imageCrop";
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: "sanity.imageHotspot";
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageAsset = {
	_id: string;
	_type: "sanity.imageAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: "sanity.assetSourceData";
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageMetadata = {
	_type: "sanity.imageMetadata";
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Slug = {
	_type: "slug";
	current?: string;
	source?: string;
};

export type AllSanitySchemaTypes =
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| BehindTheScenesBlock
	| TechSpecsBlock
	| FeaturedImageBlock
	| QuoteBlock
	| DividerBlock
	| DemoBlock
	| RepoLinkBlock
	| ChallengeBlock
	| ProcessBlock
	| StackBlock
	| CodeBlock
	| GalleryBlock
	| ImageBlock
	| TextBlock
	| HeadlineBlock
	| Handcrafted
	| Development
	| SoftwareType
	| Design
	| Photography
	| Geopoint
	| SanityFileAsset
	| Lens
	| Camera
	| Author
	| SanityImageCrop
	| SanityImageHotspot
	| SanityImageAsset
	| SanityAssetSourceData
	| SanityImageMetadata
	| Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
